[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "Buttonless"
opacity = 0.97
blur = true
option_as_alt = "Both"
