[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 14
decorations = "Buttonless"
opacity = 0.97
blur = true
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 16
